### ISSUE TITLE
Would you pls tell how to make scroll items list on Kha ?

### ISSUE THREAD

**Issue by nvcken** [tienery/KhaTextBox#8]

**Comment by tienery** [comment]
What do you mean by scroll items list? Or do you mean a list of items that scrolls? It's hardly complicated. All you need to do is track mouseDown, mouseUp, and MouseWheel events, draw your list around `g2.scissor` and update the items accordingly. For scrolling, you just need to draw all the items, find out the max height of the contents and use the max height to set the maximum scroll down.

I realise you are clearly trying to find GUI that is simple and easy to use, and I myself have been finding one myself (I've settled with dear imgui and it's C# binding, ridiculously easy to use), but this is outside the context of this library. If you want to settle for something similar in Haxe, I would suggest [zui](https://github.com/armory3d/zui).

For questions like this, I would appreciate it if you went onto the [Haxe forums](https://community.haxe.org/) and asked there as you will get better answers from better skilled people than I.
